# Generated by Django 4.2.7 on 2023-11-28 15:20

from django.db import migrations
import marketplace.apps.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', marketplace.apps.authentication.models.CustomerManager()),
            ],
        ),
    ]
